#!/usr/bin/env bash

# Opens an IDE while sourcing the suitable ROS workspace

# file was given, check if we are in a ROS 1 workspace
if [[ ! -z $2 ]]; then
    for ws in $ros1_workspaces; do
        # if in this workspace, run colcon
        if [[ "$2" = "$ws/"* ]]; then
            ros1ws -
            $@
            exit
        fi
    done
fi

# otherwise defaults to ROS 2
ros2ws -
$@
